// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationMVC.Data;

namespace WebApplicationMVC.Migrations
{
    [DbContext(typeof(GestaoDbContext))]
    [Migration("20210716160451_RemoveTestMigration")]
    partial class RemoveTestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplicationMVC.Models.Diretor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeDiretor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("OscarFilmesDirigidos")
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoraId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoraId");

                    b.ToTable("Diretores");
                });

            modelBuilder.Entity("WebApplicationMVC.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AluguelSemana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Avaliacao")
                        .HasColumnType("int");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiretorGeralId")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("IdProdutora")
                        .HasColumnType("int");

                    b.Property<bool>("Oscar")
                        .HasColumnType("bit");

                    b.Property<int?>("ProdutoraResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("DiretorGeralId");

                    b.HasIndex("ProdutoraResponsavelId");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("WebApplicationMVC.Models.Produtora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeFundador")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NomeProdutora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Oscars")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPatrimonial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtoras");
                });

            modelBuilder.Entity("WebApplicationMVC.Models.Diretor", b =>
                {
                    b.HasOne("WebApplicationMVC.Models.Produtora", "Produtora")
                        .WithMany("Diretores")
                        .HasForeignKey("ProdutoraId");

                    b.Navigation("Produtora");
                });

            modelBuilder.Entity("WebApplicationMVC.Models.Filme", b =>
                {
                    b.HasOne("WebApplicationMVC.Models.Diretor", "DiretorGeral")
                        .WithMany()
                        .HasForeignKey("DiretorGeralId");

                    b.HasOne("WebApplicationMVC.Models.Produtora", "ProdutoraResponsavel")
                        .WithMany()
                        .HasForeignKey("ProdutoraResponsavelId");

                    b.Navigation("DiretorGeral");

                    b.Navigation("ProdutoraResponsavel");
                });

            modelBuilder.Entity("WebApplicationMVC.Models.Produtora", b =>
                {
                    b.Navigation("Diretores");
                });
#pragma warning restore 612, 618
        }
    }
}
